# #
#   Searxico Favicon Cloudflare Worker
# #

name = "searxico"
main = "src/index.js"
workers_dev = true
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-09-23"

# The rate limiting API is in open beta.
[[unsafe.bindings]]
name = "searxico"
type = "ratelimit"
namespace_id = "1001"
simple = { limit = 30, period = 60 }

# env variables
[vars]
THROTTLE_DELAY_MS = 0
THROTTLE_AGGRESSIVE = false
THROTTLE_AGGRESSIVE_PUNISH_MS = 5000
THROTTLE_DAILY_ENABLED = false
THROTTLE_DAILY_LIMIT = 2000

[observability]
enabled = true
