# #
#   Searxico Favicon Cloudflare Worker
# #

name = "searxico"
main = "src/index.js"
compatibility_date = "2024-10-06"
workers_dev = true
node_compat = true

# The rate limiting API is in open beta.
[[unsafe.bindings]]
name = "searxico"
type = "ratelimit"
namespace_id = "1001"
simple = { limit = 30, period = 60 }

# env variables
[vars]
THROTTLE_DELAY_MS = 0
THROTTLE_AGGRESSIVE = false
THROTTLE_AGGRESSIVE_PUNISH_MS = 5000
THROTTLE_DAILY_ENABLED = false
THROTTLE_DAILY_LIMIT = 2000
